version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      - run: docker build -t eshop:$CIRCLE_SHA1 -f src/Web/Dockerfile .
  test:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
         requires: 
           - test
      - test
