version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      - run: |
          docker build -t local -f src/Web/Dockerfile .
  test:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet test
  push:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run: |
         pip install aws-cli
         eval $(aws ecr get-login --no-include-email --region us-east-1)
         docker tag local $REGISTRY:$CIRCLE_SHA1 
         docker push $REGISTRY:$CIRCLE_SHA1
       
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
         requires: 
           - test
      - test
      - push:
         requires:
           - build
