version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run: docker build -t jloper3/eshop:$CIRCLE_SHA1
  test:
    docker:
      - image: docker
    steps:
      - checkout
      - run: echo hi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
