version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true 
      - run: |
          echo moved #docker build -t local:$CIRCLE_SHA1 -f src/Web/Dockerfile .
  test:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: echo testme #dotnet test
  push:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
         docker build -t local:$CIRCLE_SHA1 -f src/Web/Dockerfile .
         python3 -m venv venv
         . venv/bin/activate
         pip install awscli
         eval $(aws ecr get-login --no-include-email --region us-east-1)
         docker tag local:$CIRCLE_SHA1 $REGISTRY:$CIRCLE_SHA1 
         docker push $REGISTRY:$CIRCLE_SHA1
         curl -k -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
         chmod +x /usr/local/bin/aws-iam-authenticator
         aws eks update-kubeconfig --name Cluster-sXlPflDQXLqR          
         envsubst < deployment.yaml 
       
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
         requires: 
           - test
      - test
      - push:
         requires:
           - build
